// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int nTimes = Integer.parseInt(args[0]);

		int greater = 0;
		int lessEqual = 0;
		
		for (int i = 0; i < nTimes; i++) {
		double randomNumber = Math.random();
		
		if (randomNumber > 0.5) {
			greater++;
		} else {
			lessEqual++;
		}

		}

		double ratio = (double) greater / lessEqual;

		System.out.println("> 0.5: " + greater + " times");
        System.out.println("<= 0.5: " + lessEqual + " times");
        System.out.println("Ratio: " + ratio);



	}
}
